[workflow]
name = 'bam_to_cram'

populate_assays = true

[workflow.bam_to_cram]
analysis_type = 'cram'

[workflow.resource_overrides.bam_to_cram]
# cpu_cores = 1
# storage_gib = 50

[images]
somalier = "australia-southeast1-docker.pkg.dev/cpg-common/images/somalier:0.2.15"

[references]
somalier_sites = "gs://cpg-common-main/references/somalier/sites.hg38.vcf.gz"
